# bASIC
runtime: nodejs
env: flex

# Skip uloading node_modules
skip_files:
- node_modules
- source

# # Handlers
# handlers:
# - url: /.*
#   script: auto
#   http_headers:
#     X-Forwarded-Proto: https
